PRAGMA encoding="UTF-8";
PRAGMA foreign_keys = ON;

DROP TABLE IF EXISTS DEZENA_SIMULACAO;
DROP TABLE IF EXISTS SIMULACAO;
DROP TABLE IF EXISTS EXECUCAO;
DROP TABLE IF EXISTS DEZENA_PREVISTA;
DROP TABLE IF EXISTS CONCURSO;
DROP TABLE IF EXISTS RESULTADO;
DROP TABLE IF EXISTS DEZENA_INDICE;
DROP TABLE IF EXISTS DEZENA_FREQUENCIA;
DROP TABLE IF EXISTS DEZENA;

CREATE TABLE CONCURSO (
	ID_CONCURSO INTEGER,
	NUMERO INTEGER, 
	PRIMARY KEY (ID_CONCURSO),
	UNIQUE(NUMERO)
);

CREATE TABLE DEZENA_PREVISTA (
	ID_DEZENA_PREVISTA INTEGER,
	NUMERO_CONCURSO INTEGER,
	DEZENA INTEGER,
	SORTEADA BOOL,
	PRIMARY KEY (ID_DEZENA_PREVISTA),
	UNIQUE(NUMERO_CONCURSO, DEZENA),
	FOREIGN KEY(NUMERO_CONCURSO) REFERENCES CONCURSO(NUMERO) ON DELETE CASCADE
);

--ENUM('INICIADA', 'FINALIZADA_COM_SUCESSO', 'FINALIZADA_COM_ERRO'),
CREATE TABLE EXECUCAO (
	ID_EXECUCAO INTEGER,
	CONCURSO INTEGER, 
	DATA_INICIO DATETIME,
	DATA_FIM DATETIME,
	STATUS INTEGER CHECK(STATUS in (1,2,3)), 
	PRIMARY KEY (ID_EXECUCAO)
);

CREATE TABLE RESULTADO (
	ID_RESULTADO INTEGER,
	NUMERO INTEGER, 
	DATA DATE,
	DEZENA_1 INTEGER,
	DEZENA_2 INTEGER,
	DEZENA_3 INTEGER,
	DEZENA_4 INTEGER,	
	DEZENA_5 INTEGER,
	DEZENA_6 INTEGER,
	PRIMARY KEY (ID_RESULTADO),
	UNIQUE(NUMERO)
);

CREATE TABLE DEZENA(
	ID_DEZENA INTEGER,
	CONCURSO INTEGER,
	VALOR INTEGER,
	DEZENA INTEGER,
	PRIMARY KEY(ID_DEZENA),
	UNIQUE(CONCURSO, VALOR)
);

CREATE TABLE DEZENA_FREQUENCIA(
	ID_DEZENA_FREQUENCIA INTEGER,
	CONCURSO INTEGER,
	VALOR INTEGER,
	FREQUENCIA INTEGER,
	CONCURSOS_ATRAS INTEGER,
	PROXIMO_CONCURSO INTEGER,
	UNIQUE(CONCURSO, VALOR),
	PRIMARY KEY(ID_DEZENA_FREQUENCIA)
);

CREATE TABLE DEZENA_INDICE(
	ID_DEZENA_INDICE INTEGER,
	CONCURSO INTEGER,
	VALOR INTEGER,
	INDICE_PREVISAO FLOAT,
	INDICE_CONCURSOS_ATRAS FLOAT,
	INDICE_FREQUENCIA FLOAT,
	INDICE FLOAT,
	UNIQUE(CONCURSO, VALOR),
	PRIMARY KEY(ID_DEZENA_INDICE)
);

CREATE TABLE SIMULACAO (
	ID_SIMULACAO INTEGER,
	NUMERO_CONCURSO INTEGER,
	NUMERO_SIMULACOES INTEGER,
	PRIMARY KEY(ID_SIMULACAO),
	UNIQUE(NUMERO_CONCURSO)
);

CREATE TABLE DEZENA_SIMULACAO(
	ID INTEGER,
	NUMERO_CONCURSO INTEGER,
	VALOR INTEGER,
	FREQUENCIA INTEGER,
	PRIMARY KEY(ID),
	UNIQUE(NUMERO_CONCURSO, VALOR),
	FOREIGN KEY(NUMERO_CONCURSO) REFERENCES SIMULACAO(NUMERO_CONCURSO) ON DELETE CASCADE
);